// ─── HerNest Unified Insight Engine ──────────────────────────────
// Generates, ranks, filters, deduplicates, and manages lifecycle
// for household insights across all modules.
//
// Philosophy:
// - Rules-based first (fast, explainable, no AI cost)
// - AI only for synthesis, wording, cross-module patterns
// - Calm over noise — every insight must earn its place
// - State-aware — overloaded households see fewer insights
//
// Extends existing HouseholdInsight type from store.ts

import type { HouseholdInsight, InsightCategory } from "../store";
import type { AppContext } from "../contextBuilder";
import type { HouseholdStateResult } from "../household/householdStateEngine";
import { aiJSON } from "../ai";
import { saveData, loadData } from "../firebase";
import { bus } from "../events";

// ═══════════════════════════════════════════════════════════════════
// EXTENDED TYPES
// Builds on existing HouseholdInsight without breaking existing code
// ═══════════════════════════════════════════════════════════════════

export type InsightType =
  | "risk"
  | "opportunity"
  | "reminder"
  | "pattern"
  | "recommendation"
  | "forecast"
  | "celebration";

export type InsightSeverity = "low" | "medium" | "high";

export type InsightStatus =
  | "active"
  | "viewed"
  | "acted_on"
  | "snoozed"
  | "dismissed"
  | "expired";

export type InsightAction = {
  label: string;
  actionType:
    | "open_module"
    | "create_task"
    | "adjust_budget"
    | "create_goal"
    | "ask_nora"
    | "schedule_review"
    | "dismiss"
    | "snooze";
  targetModule?: string;
};

export interface RichInsight extends HouseholdInsight {
  // Extended fields (all optional for backward compatibility)
  title?: string;
  summary?: string;
  type?: InsightType;
  severity?: InsightSeverity;
  status?: InsightStatus;
  actions?: InsightAction[];
  expiresAt?: string;
  snoozedUntil?: string;
  explanation?: {
    contextUsed: string[];
    assumptions: string[];
    confidenceReason: string;
  };
  ruleId?: string;        // set if generated by a rule
  scored?: number;        // final ranking score 0–100
}

export interface InsightScore {
  urgency:       number; // 0–100 time sensitivity
  importance:    number; // 0–100 consequence if ignored
  confidence:    number; // 0–100 quality of evidence
  actionability: number; // 0–100 can user do something?
  novelty:       number; // 0–100 not recently shown
  stateFit:      number; // 0–100 matches household state
}

// ═══════════════════════════════════════════════════════════════════
// COOLDOWN REGISTRY
// Prevents the same insight type from showing repeatedly
// ═══════════════════════════════════════════════════════════════════

const COOLDOWNS: Record<string, number> = {
  delivery_busy_week:         14,
  goal_off_track:             10,
  task_backlog_high:           7,
  school_expense_upcoming:     7,
  routine_missed:              7,
  calendar_overload:           5,
  financial_risk:              7,
  travel_prep_incomplete:      3,
  savings_rate_low:           14,
  subscription_creep:         21,
  cash_flow_projection:        5,
};

function isOnCooldown(ruleId: string, existing: RichInsight[]): boolean {
  const cooldownDays = COOLDOWNS[ruleId] ?? 7;
  const cutoff = Date.now() - cooldownDays * 24 * 60 * 60 * 1000;
  return existing.some(i =>
    i.ruleId === ruleId &&
    new Date(i.createdAt).getTime() > cutoff &&
    i.status !== "dismissed"
  );
}

// ═══════════════════════════════════════════════════════════════════
// RULES ENGINE
// Each rule is a pure function: context → insight | null
// ═══════════════════════════════════════════════════════════════════

type InsightRule = {
  id: string;
  check: (ctx: AppContext) => RichInsight | null;
};

const RULES: InsightRule[] = [

  // ── Rule 1: Busy calendar + delivery spending ──────────────────
  {
    id: "delivery_busy_week",
    check: (ctx) => {
      const isHeavy = ["heavy", "extreme"].includes(ctx.calendar.density);
      const dining  = ctx.budget.categoryAlerts.find(c =>
        c.name.toLowerCase().includes("dining") && c.pct > 80
      );
      if (!isHeavy || !dining) return null;
      return {
        id: crypto.randomUUID(),
        ruleId: "delivery_busy_week",
        title: "Busy week may be driving dining spend",
        summary: "Your calendar is heavy this week and dining/delivery is trending up.",
        category: "spending" as InsightCategory,
        type: "pattern" as InsightType,
        severity: "medium" as InsightSeverity,
        observation: `Calendar is ${ctx.calendar.density} this week and dining/delivery is at ${dining.pct}% of budget.`,
        whyItMatters: "Planning two quick meals this week could prevent budget pressure.",
        recommendation: "Plan two easy dinners and set a delivery limit for the rest of the week.",
        options: ["Plan meals Sunday", "Set a $30 delivery budget cap", "Order in batches not individually"],
        confidenceLevel: 65,
        sourceModules: ["calendar", "budget"] as any,
        status: "active" as InsightStatus,
        explanation: {
          contextUsed: ["Calendar density", "Dining category spend"],
          assumptions: ["Delivery spending correlates with busy weeks"],
          confidenceReason: "Pattern based on current week data only",
        },
        actions: [
          { label: "View Budget", actionType: "open_module", targetModule: "finances" },
          { label: "Ask Nora", actionType: "ask_nora" },
        ],
        createdAt: new Date().toISOString(),
        expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      };
    },
  },

  // ── Rule 2: Vacation goal off track ───────────────────────────
  {
    id: "goal_off_track",
    check: (ctx) => {
      const atRisk = ctx.budget.savingsGoals.find(g => g.pct < 40);
      if (!atRisk) return null;
      const gap = 100 - atRisk.pct;
      return {
        id: crypto.randomUUID(),
        ruleId: "goal_off_track",
        title: `${atRisk.name} goal needs attention`,
        summary: `The ${atRisk.name} goal is at ${atRisk.pct}% — catching this early keeps options open.`,
        category: "savings" as InsightCategory,
        type: "forecast" as InsightType,
        severity: gap > 60 ? "high" : "medium" as InsightSeverity,
        observation: `${atRisk.name} is ${atRisk.pct}% funded with the target approaching.`,
        whyItMatters: "Addressing a goal shortfall early gives more options than waiting.",
        recommendation: `Increase monthly contribution or adjust the ${atRisk.name} target slightly.`,
        options: ["Increase contribution", "Adjust goal target", "Delay goal date", "Ask Nora for scenarios"],
        confidenceLevel: 75,
        sourceModules: ["budget", "goals"] as any,
        status: "active" as InsightStatus,
        explanation: {
          contextUsed: ["Savings goals", "Current funding percentage"],
          assumptions: ["Goal target and timeline are unchanged"],
          confidenceReason: "Based on current savings data",
        },
        actions: [
          { label: "View Goals", actionType: "open_module", targetModule: "finances" },
          { label: "Run Scenario", actionType: "ask_nora" },
        ],
        createdAt: new Date().toISOString(),
      };
    },
  },

  // ── Rule 3: High task backlog ──────────────────────────────────
  {
    id: "task_backlog_high",
    check: (ctx) => {
      const overdue = ctx.tasks.overdue.length;
      const total   = ctx.tasks.total;
      if (overdue < 3 && total < 10) return null;
      return {
        id: crypto.randomUUID(),
        ruleId: "task_backlog_high",
        title: "Task backlog is building up",
        summary: `${overdue} overdue tasks and ${total} total pending — a quick sort could help.`,
        category: "stress" as InsightCategory,
        type: "recommendation" as InsightType,
        severity: overdue >= 5 ? "high" : "medium" as InsightSeverity,
        observation: `${overdue} tasks are overdue. ${total} total tasks pending.`,
        whyItMatters: "A growing backlog increases mental load even when tasks aren't urgent.",
        recommendation: "Spend 10 minutes sorting tasks: keep 3 for today, defer or delete the rest.",
        options: ["Do a 10-min task sort", "Ask Nora to prioritize", "Defer everything non-urgent"],
        confidenceLevel: 80,
        sourceModules: ["tasks"] as any,
        status: "active" as InsightStatus,
        explanation: {
          contextUsed: ["Task overdue count", "Total pending tasks"],
          assumptions: ["All listed tasks are still relevant"],
          confidenceReason: "Based on current task data",
        },
        actions: [
          { label: "Open Tasks", actionType: "open_module", targetModule: "tasks" },
          { label: "Ask Nora to Prioritize", actionType: "ask_nora" },
        ],
        createdAt: new Date().toISOString(),
      };
    },
  },

  // ── Rule 4: Upcoming school expense + low cash ────────────────
  {
    id: "school_expense_upcoming",
    check: (ctx) => {
      const schoolItems = ctx.school.thisWeek.length + ctx.school.urgentToday.length;
      const cashLow = ctx.budget.status === "warning" || ctx.budget.status === "critical";
      if (schoolItems < 2 || !cashLow) return null;
      return {
        id: crypto.randomUUID(),
        ruleId: "school_expense_upcoming",
        title: "School activity + budget pressure this week",
        summary: "School events are coming up while the budget is under some pressure.",
        category: "scheduling" as InsightCategory,
        type: "risk" as InsightType,
        severity: "medium" as InsightSeverity,
        observation: `${schoolItems} school items this week and spending is at ${ctx.budget.status} level.`,
        whyItMatters: "Planning ahead prevents last-minute spending surprises.",
        recommendation: "Check school event costs now and reserve a small buffer in the budget.",
        options: ["Review school costs", "Adjust budget temporarily", "Ask Nora for a plan"],
        confidenceLevel: 70,
        sourceModules: ["school", "budget"] as any,
        status: "active" as InsightStatus,
        explanation: {
          contextUsed: ["School events this week", "Budget status"],
          assumptions: ["School events may have associated costs"],
          confidenceReason: "Based on school calendar and budget data",
        },
        actions: [
          { label: "View Finances", actionType: "open_module", targetModule: "finances" },
          { label: "Ask Nora", actionType: "ask_nora" },
        ],
        createdAt: new Date().toISOString(),
      };
    },
  },

  // ── Rule 5: Travel prep incomplete ────────────────────────────
  {
    id: "travel_prep_incomplete",
    check: (ctx) => {
      const trip = ctx.trips.next;
      if (!trip || trip.daysUntil > 14 || trip.packingPct > 60) return null;
      return {
        id: crypto.randomUUID(),
        ruleId: "travel_prep_incomplete",
        title: `${trip.dest} trip is ${trip.daysUntil} days away`,
        summary: `Packing is ${trip.packingPct}% done with ${trip.daysUntil} days to go.`,
        category: "scheduling" as InsightCategory,
        type: "reminder" as InsightType,
        severity: trip.daysUntil <= 7 ? "high" : "medium" as InsightSeverity,
        observation: `${trip.dest} trip in ${trip.daysUntil} days. Packing list is ${trip.packingPct}% complete.`,
        whyItMatters: "Starting packing early reduces pre-trip stress significantly.",
        recommendation: "Set aside 20 minutes to work through the packing list.",
        options: ["Open packing list", "Ask Nora to generate packing list", "Set a packing reminder"],
        confidenceLevel: 90,
        sourceModules: ["trips"] as any,
        status: "active" as InsightStatus,
        explanation: {
          contextUsed: ["Trip date", "Packing completion percentage"],
          assumptions: [],
          confidenceReason: "Based on trip data and packing list",
        },
        actions: [
          { label: "Open Trips", actionType: "open_module", targetModule: "trips" },
        ],
        createdAt: new Date().toISOString(),
      };
    },
  },

  // ── Rule 6: Low savings rate ──────────────────────────────────
  {
    id: "savings_rate_low",
    check: (ctx) => {
      if (ctx.budget.monthlyIncome === 0) return null;
      if (ctx.budget.savingsRate >= 10) return null;
      return {
        id: crypto.randomUUID(),
        ruleId: "savings_rate_low",
        title: "Savings rate has room to grow",
        summary: `Current savings rate is ${ctx.budget.savingsRate.toFixed(0)}% — even small increases compound quickly.`,
        category: "savings" as InsightCategory,
        type: "opportunity" as InsightType,
        severity: "low" as InsightSeverity,
        observation: `Savings rate is ${ctx.budget.savingsRate.toFixed(1)}% of income.`,
        whyItMatters: "A 5% savings rate increase on your income adds meaningful cushion over time.",
        recommendation: "Identify one spending category to reduce slightly and redirect to savings.",
        options: ["Review spending categories", "Create a savings goal", "Ask CFO for a plan"],
        confidenceLevel: 70,
        sourceModules: ["budget"] as any,
        status: "active" as InsightStatus,
        explanation: {
          contextUsed: ["Monthly income", "Total spending", "Savings rate calculation"],
          assumptions: ["Income and spending figures are current month"],
          confidenceReason: "Based on income and spending data",
        },
        actions: [
          { label: "View Budget", actionType: "open_module", targetModule: "finances" },
          { label: "Ask CFO", actionType: "ask_nora" },
        ],
        createdAt: new Date().toISOString(),
      };
    },
  },

  // ── Rule 7: Month-end overspend projection ────────────────────
  {
    id: "cash_flow_projection",
    check: (ctx) => {
      const projected = ctx.budget.projected;
      const limit = ctx.budget.limit;
      if (limit === 0 || projected <= limit * 1.05) return null;
      const overshoot = projected - limit;
      return {
        id: crypto.randomUUID(),
        ruleId: "cash_flow_projection",
        title: "Month-end spending may exceed budget",
        summary: `At this pace, spending will exceed budget by about $${Math.round(overshoot).toLocaleString()}.`,
        category: "cashflow" as InsightCategory,
        type: "forecast" as InsightType,
        severity: overshoot > limit * 0.15 ? "high" : "medium" as InsightSeverity,
        observation: `Projected month-end: $${Math.round(projected).toLocaleString()} vs budget of $${limit.toLocaleString()}.`,
        whyItMatters: "Adjusting one or two categories now avoids a larger shortfall at month end.",
        recommendation: `Reduce spending in your highest variable category by ~$${Math.round(overshoot / 2).toLocaleString()} for the rest of the month.`,
        options: ["Review highest spend categories", "Pause discretionary spending", "Ask CFO for options"],
        confidenceLevel: 75,
        sourceModules: ["budget"] as any,
        status: "active" as InsightStatus,
        explanation: {
          contextUsed: ["Daily spending rate", "Days remaining", "Budget limit"],
          assumptions: ["Spending pace continues at current rate"],
          confidenceReason: "Linear projection from current spending rate",
        },
        actions: [
          { label: "View Budget", actionType: "open_module", targetModule: "finances" },
          { label: "Ask CFO", actionType: "ask_nora" },
        ],
        createdAt: new Date().toISOString(),
      };
    },
  },

  // ── Rule 8: Subscription creep ────────────────────────────────
  {
    id: "subscription_creep",
    check: (ctx) => {
      const subCat = ctx.budget.categoryAlerts.find(c =>
        c.name.toLowerCase().includes("subscription") && c.pct > 70
      );
      if (!subCat) return null;
      return {
        id: crypto.randomUUID(),
        ruleId: "subscription_creep",
        title: "Subscriptions worth reviewing",
        summary: "Subscription spending is elevated — a quick audit often finds unused services.",
        category: "spending" as InsightCategory,
        type: "opportunity" as InsightType,
        severity: "low" as InsightSeverity,
        observation: `Subscriptions at ${subCat.pct}% of category budget.`,
        whyItMatters: "The average household has 3–4 unused subscriptions adding $30–60/month.",
        recommendation: "Spend 10 minutes reviewing active subscriptions and cancel any unused ones.",
        options: ["Review subscription list", "Cancel one unused service", "Ask Nora to audit"],
        confidenceLevel: 60,
        sourceModules: ["budget"] as any,
        status: "active" as InsightStatus,
        explanation: {
          contextUsed: ["Subscription category spending"],
          assumptions: ["Some subscriptions may be unused"],
          confidenceReason: "Based on subscription category data only",
        },
        actions: [
          { label: "View Budget", actionType: "open_module", targetModule: "finances" },
          { label: "Ask Nora", actionType: "ask_nora" },
        ],
        createdAt: new Date().toISOString(),
      };
    },
  },
];

// ═══════════════════════════════════════════════════════════════════
// SCORING ENGINE
// Ranks insights by weighted score
// ═══════════════════════════════════════════════════════════════════

function scoreInsight(
  insight: RichInsight,
  householdState: HouseholdStateResult | null,
  existing: RichInsight[]
): number {
  const urgencyMap: Record<InsightSeverity, number> = {
    high: 80, medium: 50, low: 20
  };
  const urgency       = urgencyMap[insight.severity ?? "medium"];
  const importance    = insight.confidenceLevel ?? 50;
  const confidence    = insight.confidenceLevel ?? 50;
  const actionability = (insight.actions?.length ?? 0) > 0 ? 75 : 30;

  // Novelty: penalize if similar insight was recently shown
  const recentSimilar = existing.filter(e =>
    e.category === insight.category &&
    e.ruleId === insight.ruleId &&
    e.status !== "dismissed" &&
    new Date(e.createdAt).getTime() > Date.now() - 3 * 24 * 60 * 60 * 1000
  ).length;
  const novelty = recentSimilar > 0 ? 10 : 80;

  // State fit: does this insight match the current household state?
  let stateFit = 50;
  if (householdState) {
    const primaryState = householdState.primary.state;
    const catStateMap: Partial<Record<InsightCategory, string[]>> = {
      spending:       ["financial_pressure", "busy", "overloaded"],
      savings:        ["calm", "financial_pressure"],
      cashflow:       ["financial_pressure"],
      stress:         ["overloaded", "busy"],
      scheduling:     ["busy", "overloaded", "travel_prep", "school_transition"],
      opportunity:    ["calm", "recovery"],
      decision:       ["decision_heavy"],
    };
    const goodStates = catStateMap[insight.category] ?? [];
    stateFit = goodStates.includes(primaryState) ? 90 : 40;
  }

  return Math.round(
    urgency       * 0.25 +
    importance    * 0.25 +
    confidence    * 0.20 +
    actionability * 0.15 +
    stateFit      * 0.10 +
    novelty       * 0.05
  );
}

// ═══════════════════════════════════════════════════════════════════
// STATE-AWARE FILTER
// Limits insight count and types based on household state
// ═══════════════════════════════════════════════════════════════════

function filterByState(
  insights: RichInsight[],
  householdState: HouseholdStateResult | null
): RichInsight[] {
  if (!householdState) return insights.slice(0, 3);

  const state = householdState.primary.state;

  switch (state) {
    case "overloaded":
      // Max 2 insights, only high severity
      return insights
        .filter(i => i.severity === "high" || i.type === "recommendation")
        .slice(0, 2);

    case "busy":
      // Max 3 insights, skip low-severity optimizations
      return insights
        .filter(i => i.severity !== "low" || i.type === "reminder")
        .slice(0, 3);

    case "calm":
    case "recovery":
      // Show opportunities and planning insights freely
      return insights.slice(0, 4);

    case "financial_pressure":
      // Prioritize financial insights
      return [
        ...insights.filter(i => ["spending", "savings", "cashflow", "debt"].includes(i.category)),
        ...insights.filter(i => !["spending", "savings", "cashflow", "debt"].includes(i.category)),
      ].slice(0, 3);

    case "travel_prep":
      return [
        ...insights.filter(i => i.ruleId === "travel_prep_incomplete"),
        ...insights.filter(i => i.ruleId !== "travel_prep_incomplete"),
      ].slice(0, 3);

    default:
      return insights.slice(0, 3);
  }
}

// ═══════════════════════════════════════════════════════════════════
// LIFECYCLE MANAGEMENT
// ═══════════════════════════════════════════════════════════════════

export function expireOldInsights(insights: RichInsight[]): RichInsight[] {
  const now = Date.now();
  return insights.map(i => {
    if (i.expiresAt && new Date(i.expiresAt).getTime() < now) {
      return { ...i, status: "expired" as InsightStatus };
    }
    return i;
  });
}

export function markInsightViewed(insights: RichInsight[], id: string): RichInsight[] {
  return insights.map(i => i.id === id ? { ...i, status: "viewed" as InsightStatus } : i);
}

export function markInsightActedOn(insights: RichInsight[], id: string): RichInsight[] {
  return insights.map(i => i.id === id ? { ...i, status: "acted_on" as InsightStatus } : i);
}

export function dismissInsight(insights: RichInsight[], id: string): RichInsight[] {
  return insights.map(i =>
    i.id === id ? { ...i, status: "dismissed" as InsightStatus, dismissed: true } : i
  );
}

export function snoozeInsight(insights: RichInsight[], id: string, days = 3): RichInsight[] {
  const until = new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();
  return insights.map(i =>
    i.id === id ? { ...i, status: "snoozed" as InsightStatus, snoozedUntil: until } : i
  );
}

export function getActiveInsights(insights: RichInsight[]): RichInsight[] {
  const now = Date.now();
  return insights.filter(i => {
    if (i.status === "dismissed" || i.dismissed) return false;
    if (i.status === "expired") return false;
    if (i.status === "snoozed" && i.snoozedUntil && new Date(i.snoozedUntil).getTime() > now) return false;
    return true;
  });
}

// ═══════════════════════════════════════════════════════════════════
// MAIN ENGINE
// ═══════════════════════════════════════════════════════════════════

export function generateRuleBasedInsights(
  ctx: AppContext,
  existing: RichInsight[],
  householdState: HouseholdStateResult | null
): RichInsight[] {
  const generated: RichInsight[] = [];

  for (const rule of RULES) {
    // Skip if on cooldown
    if (isOnCooldown(rule.id, existing)) continue;

    try {
      const insight = rule.check(ctx);
      if (insight) generated.push(insight);
    } catch (e) {
      console.warn(`[InsightEngine] Rule ${rule.id} failed:`, e);
    }
  }

  // Score each insight
  const scored = generated.map(i => ({
    ...i,
    scored: scoreInsight(i, householdState, existing),
  }));

  // Sort by score
  scored.sort((a, b) => (b.scored ?? 0) - (a.scored ?? 0));

  // Filter by household state
  return filterByState(scored, householdState);
}

// ═══════════════════════════════════════════════════════════════════
// AI SYNTHESIS
// Called only when rule-based insights need enrichment or
// when cross-module patterns require reasoning
// ═══════════════════════════════════════════════════════════════════

export async function enrichInsightsWithAI(
  insights: RichInsight[],
  ctx: AppContext
): Promise<RichInsight[]> {
  if (insights.length === 0) return insights;

  // Only enrich cross-module insights — single-module insights are fine as-is
  const needsEnrichment = insights.filter(i =>
    (i.sourceModules?.length ?? 0) >= 2 && i.type === "pattern"
  );
  if (needsEnrichment.length === 0) return insights;

  const sys = `You are HerNest's household intelligence engine.
Improve the wording of these household insights to be warmer, more specific, and more actionable.
Do not change the facts or add invented data. Only improve clarity and tone.
Return ONLY valid JSON array of the same objects with improved title, summary, observation, whyItMatters, and recommendation fields.
Keep responses concise — each field under 2 sentences.`;

  try {
    const improved = await aiJSON<RichInsight[]>(
      sys,
      JSON.stringify(needsEnrichment.map(i => ({
        id: i.id,
        title: i.title,
        summary: i.summary,
        observation: i.observation,
        whyItMatters: i.whyItMatters,
        recommendation: i.recommendation,
      }))),
      "household_cfo",
      needsEnrichment
    );

    if (!Array.isArray(improved)) return insights;

    // Merge improved wording back
    return insights.map(i => {
      const enriched = improved.find(e => e.id === i.id);
      if (!enriched) return i;
      return {
        ...i,
        title:          enriched.title          ?? i.title,
        summary:        enriched.summary        ?? i.summary,
        observation:    enriched.observation    ?? i.observation,
        whyItMatters:   enriched.whyItMatters   ?? i.whyItMatters,
        recommendation: enriched.recommendation ?? i.recommendation,
      };
    });
  } catch (e) {
    console.warn("[InsightEngine] AI enrichment failed (non-fatal):", e);
    return insights;
  }
}

// ═══════════════════════════════════════════════════════════════════
// FIRESTORE PERSISTENCE
// ═══════════════════════════════════════════════════════════════════

export async function saveInsights(userId: string, insights: RichInsight[]): Promise<void> {
  try {
    await saveData(userId, "household_insights_v2", {
      insights,
      updatedAt: new Date().toISOString(),
    });
  } catch (e) {
    console.error("[InsightEngine] save failed:", e);
  }
}

export async function loadInsights(userId: string): Promise<RichInsight[]> {
  try {
    const data = await loadData(userId, "household_insights_v2");
    return (data?.insights as RichInsight[]) || [];
  } catch {
    return [];
  }
}

// ═══════════════════════════════════════════════════════════════════
// TOP INSIGHTS SELECTOR
// Returns the best 1–3 insights for dashboard display
// ═══════════════════════════════════════════════════════════════════

export function getTopInsights(
  insights: RichInsight[],
  max = 3
): RichInsight[] {
  return getActiveInsights(expireOldInsights(insights))
    .sort((a, b) => (b.scored ?? b.confidenceLevel ?? 0) - (a.scored ?? a.confidenceLevel ?? 0))
    .slice(0, max);
}

// ═══════════════════════════════════════════════════════════════════
// NORA EXPLANATION
// Generates a human-readable explanation of why an insight appeared
// ═══════════════════════════════════════════════════════════════════

export function explainInsight(insight: RichInsight): string {
  const sources = insight.explanation?.contextUsed ?? insight.sourceModules ?? [];
  const assumptions = insight.explanation?.assumptions ?? [];

  const lines = [
    `Nora noticed this because of: ${sources.join(", ")}.`,
    insight.explanation?.confidenceReason
      ? `Confidence: ${insight.explanation.confidenceReason}.`
      : "",
    assumptions.length
      ? `Assumptions: ${assumptions.join("; ")}.`
      : "",
  ].filter(Boolean);

  return lines.join(" ");
}
